POST http://127.0.0.1:8000/api/students/
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "birth_date": "2000-01-01",
  "contact_info": "john.doe@example.com",
  "course": 1,
  "is_non_local": true,
  "password": "student_password",
  "gender": "male"
}

###

POST http://127.0.0.1:8000/api/administration/
Content-Type: application/json

{
  "first_name": "Jane",
  "last_name": "Smith",
  "contact_info": "Smith.doe@example.com",
  "dormitory_id": 1,
  "password": "admin_password",
  "contributions": 0
}

###

POST http://127.0.0.1:8000/api/auth/token
Content-Type: application/x-www-form-urlencoded

username=john.doe@example.com&password=student_password&scope=student

###

POST http://127.0.0.1:8000/api/auth/token
Content-Type: application/x-www-form-urlencoded

username=Smith.doe@example.com&password=admin_password&scope=administrator

###

GET http://127.0.0.1:8000/api/students/


### Create a new DeaneryStaff
POST http://127.0.0.1:8000/api/deanery_staff/
Content-Type: application/json

{
  "first_name": "Alice",
  "last_name": "Johnson",
  "contact_info": "alice.johnson@example.com",
  "password": "secure_password"
}

###

### Get all DeaneryStaff
GET http://127.0.0.1:8000/api/deanery_staff/


###

# curl -X 'POST'
#  'http://127.0.0.1:8000/token'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/x-www-form-urlencoded'
#  -d 'username=deanery_staff_username&password=deanery_staff_password&scope=deanery_staff'
POST http://127.0.0.1:8000/api/auth/token
accept: application/json
Content-Type: application/x-www-form-urlencoded

username = alice.johnson@example.com &
password = secure_password &
scope = deanery_staff

###

