from .student_repo import StudentRepository
from .dormitory_repo import DormitoryRepository
from .room_repo import RoomRepository
from .violation_repo import ViolationRepository
from .administration_repo import AdministrationRepository
from .accommodation_repo import AccommodationRepository
from .deanery_staff_repo import DeaneryStaffRepository